### PR TITLE
Add Age of Empires 2 Dataset

### PR DESCRIPTION
**Pull request by nicoelbert**
This commit adds my dataset about 225.000 Age of Empires 2 matches to the list of datasets.

### CODE REVIEW

**Comment by leomaurodesenv** [comment]
Sure, but pleas - can you add the content in alphabetical order?   
Just switch it with `Animal Crossing New Horizons NookPlaza Catalog`.

**Comment by nicoelbert** [comment]
Oh damn, didn't recognize yesterday. I'll change it right away. Thanks for the feedback and adding the dataset to the list:)

**Comment by nicoelbert** [comment]
Done :)

**Comment by leomaurodesenv** [comment]
Thanks!

**Pull request merged**
